[package]
name = "raffia"
version = "0.1.0"
edition = "2021"
authors = ["Pig Fang <g-plane@hotmail.com>"]
description = "Generic parser for CSS/SCSS/Less."
repository = "https://github.com/g-plane/raffia"
license = "MIT"

[dependencies]
raffia_derive = { path = "../raffia_derive" }

[dev-dependencies]
criterion = "0.3"
parcel_css = "1.0.0-alpha.30"
swc_common = "0.27.7"
swc_css_ast = "0.107.0"
swc_css_parser = "0.116.0"

[[bench]]
name = "parse_selector"
harness = false

[[bench]]
name = "parse_stylesheet"
harness = false
