[package]
name = "raffia"
version = "0.1.0"
edition = "2021"
authors = ["Pig Fang <g-plane@hotmail.com>"]
description = "Generic parser for CSS/SCSS/Less."
repository = "https://github.com/g-plane/raffia"
license = "MIT"

[dependencies]
raffia_derive = { path = "../raffia_derive" }
